### ISSUE TITLE
'ssh' command: specify server type instead of name

### ISSUE THREAD

**Issue by ajb** [cloud66/c66toolbelt#11]
From an email I sent to Khash a while back.

> Congrats on shipping this feature. As a request for v2, I’d recommend leaving out the server name param. (Or at the least, only specifying the server type.) I have a bunch of stacks, and there’s no way I’ll remember the web server names for each.

**Comment by khash** [comment]
Servers can be identified by name (or a start of a name) or role (or start of a role) if they are unique. So connection to the web server of a stack called 'My Awesome Stack' can be done by something as short as this:

```
$ cx ssh -s m w
```
