### ISSUE TITLE
Install fails with Ruby 2.2.0

### ISSUE THREAD

**Issue by corwinkelly** [cloud66/c66toolbelt#14]
Trying to install using `gem install c66` for Ruby 2.2.0 results in the following error due to a bug in the json 1.7.7 dependency:

    ../fbuffer/fbuffer.h:175:47: error: macro "rb_str_new" requires 2 arguments, but only 1 given
     VALUE result = rb_str_new(FBUFFER_PAIR(fb));

I know the underlying bug is with the json dependency rather than the c66 gem itself, but I figured it was worth documentation.

**Comment by corwinkelly** [comment]
json-1.8.2 seems to have resolved the install issue with Ruby 2.2.0. Could the c66 gem be updated to

**Comment by khash** [comment]
Just a comment for landing here: The ruby toolbelt is deprecated, please use https://app.cloud66.com/toolbelt instead.
