### ISSUE TITLE
'ssh' command: specify stack name instead of UID

### ISSUE THREAD

**Issue by ianwalter** [cloud66/c66toolbelt#15]
Similar to #11 (but I think even more important) would be to be able to specify the stack name instead of the hard-to-remember UID.

**Comment by khash** [comment]
This is already possible. You can use the name (or a unique part of it) for any command that requires a stack. If there are more than one stack with the same name, the `-e` (environment) option can be used to identify only one.

As for #11, servers can be identified by IP, name (or part of name) and role (or part of role).

**Comment by ianwalter** [comment]
Thanks, turns out I was using the c66 gem instead of the `cx` toolbelt.
